name: Check the locale of GitHub Action Runner

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  default-locale:
    runs-on: ubuntu-latest

    steps:
      - name: Show the current locale
        run: locale

  change-locale:
    runs-on: ubuntu-latest

    env:
      LC_ALL: ja_JP.UTF-8

    steps:
      - name: Show the current locale
        run: locale
